### PR TITLE
PtrToStringBSTR Fixes for Linux

### PR DESCRIPTION
**Pull request by jmilczek**
Replaced PtrToStringAuto with PtrToStringBSTR to eliminate issue with Linux OS.
https://github.com/PowerShell/PowerShell/issues/13494

### CODE REVIEW

**Comment by dennismdejong** [comment]
Can someone please handle this PR it is bugging me a lot, or tell me how I can handle it myself

**Comment by darrenjrobinson** [comment]
My bad in missing this whilst moving house. 
Will check it out and look to merge and update the module this week.

**Comment by jmilczek** [comment]
Thank youOn Nov 1, 2023, at 7:43 PM, Darren Robinson ***@***.***> wrote:﻿
My bad in missing this whilst moving house.
Will check it out and look to merge and update the module this week.

**Comment by darrenjrobinson** [comment]
Regression tested and validated on Windows.
Merged into a new branch v1.1.7 and signed. 
Please download from here and validate. 
https://github.com/darrenjrobinson/powershell_module_identitynow/tree/v1.1.7

**Comment by dennismdejong** [comment]
Works again on my MacBook and Linux agents, thanks!

**Comment by darrenjrobinson** [comment]
Excellent.
Will look to merge to master and publish to the PSGallery tomorrow morning.

**Pull request merged**
